server:
  port: 8080
  context-path: /client1

security:
  oauth2:
    client:
      client-id: zjx1
      client-secret: zjxsecret1
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key


