server:
  port: 80
  session:
    timeout: 100

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///securitydemo?useSSL=true
    username: root
    password: lawpress
  session:
    store-type: redis
  redis:
    host: 129.0.12.65
    port: 6379
#security:
#  basic:
#    enabled: false


zjx:
  security:
    social:
      filterProcessesUrl: /qqLogin
      qq:
        app-id: 101537529
        app-secret: 6ed14dbea588018f72b53d1428437710
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
    browser:
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
#    code:
#      image:
#        length: 5
#        width: 100
#        url: /user/*
    o-auth2:
      clients[0]:
        clientId: zjx
        clientSecret: zjxsecret
        accessTokenValiditySeconds: 3600
        authorizedGrantTypes[0]: refresh_token
        authorizedGrantTypes[1]: password
        scopes[0]: all
        scopes[1]: read
        scopes[2]: write
      clients[1]:
        clientId: test
        clientSecret: test
#        accessTokenValiditySeconds: 3600
        authorizedGrantTypes[0]: refresh_token
        authorizedGrantTypes[1]: password
        scopes[0]: all
        scopes[1]: read
        scopes[2]: write

#security:
#  oauth2:
#    client:
#      client-id: zjx
#      client-secret: zjxsecret
