server:
  port: 80
  session:
    timeout: 10

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///securitydemo?useSSL=true
    username: root
    password: lawpress
  session:
    store-type: none
#security:
#  basic:
#    enabled: false


zjx:
  security:
    social:
      filterProcessesUrl: /qqLogin
      qq:
        app-id: 101537529
        app-secret: 6ed14dbea588018f72b53d1428437710
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
    browser:
      signUpUrl: /demo-signUp.html
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
#    code:
#      image:
#        length: 4
#        width: 100
#        url: /user/*