spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///securitydemo?useSSL=true
    username: root
    password: lawpress
  session:
    store-type: none
security:
  basic:
    enabled: true

zjx:
  security:
#    browser:
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
    code:
      image:
        length: 6
        width: 100
        url: /user/*